In [1]:
import numpy as np
import torch

In [2]:
a=np.array([2,2.3])

In [3]:
# 创建Tensor

# 1.直接从numpy引入
torch.from_numpy(a)

tensor([2.0000, 2.3000], dtype=torch.float64)

In [4]:
a=np.ones([2,3])

In [5]:
torch.from_numpy(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [6]:
# 2.从list中引入
torch.tensor([2., 3.2])
# .tensor()与.Tensor()的区别
#  .tensor()接收现成的数据，.Tensor()接收shape，
# 而.Tensor([])则也能接收现成数据（尽量避免这样使用）。

tensor([2.0000, 3.2000])

In [7]:
torch.tensor([[2., 3.2], [1., 22.3]])

tensor([[ 2.0000,  3.2000],
        [ 1.0000, 22.3000]])

In [8]:
# 定义未初始化的数据

torch.empty(1)

tensor([8.4490e-39])

In [9]:
torch.Tensor(2,3)
# 未初始化的数据过于随机,不建议未覆盖直接使用

tensor([[3.3241e+21, 1.7661e-04, 2.7177e+23],
        [6.7577e-07, 4.2700e-08, 2.1749e+23]])

In [10]:
torch.IntTensor(2,3)

tensor([[48, 58, 53],
        [48, 58, 51]], dtype=torch.int32)

In [11]:
torch.FloatTensor(2,3)

tensor([[2.0317e+20, 1.0528e-11, 1.0524e+21],
        [2.7150e-06, 1.0779e-08, 6.3008e-10]])

In [12]:
# 使用.tensor()直接创建的tensor为默认类型FloatTensor
torch.tensor([1.2, 3]).type()

'torch.FloatTensor'

In [13]:
torch.set_default_tensor_type(torch.DoubleTensor)

In [14]:
torch.tensor([1.2, 3]).type()

'torch.DoubleTensor'

In [15]:
# 随机初始化

# 1.使用rand()随机产生从[0,1)之间均匀采样的数
torch.rand(3,3)

tensor([[0.4638, 0.8737, 0.1398],
        [0.7416, 0.9217, 0.8216],
        [0.7872, 0.2363, 0.9525]])

In [16]:
a=torch.rand(3,3)

In [17]:
torch.rand_like(a)  # 依照a的shape用rand()生成tensor

tensor([[0.3404, 0.0704, 0.6983],
        [0.0421, 0.6318, 0.9572],
        [0.3838, 0.1888, 0.7294]])

In [18]:
torch.randint(1,10,[3,3])  # randint(min,max,shape)

tensor([[9, 7, 2],
        [6, 5, 4],
        [5, 4, 2]])

In [19]:
# 2.使用randn()产生随机从均值为0,方差为1的正态分布之间均匀采样的数
torch.randn(3,3)

tensor([[ 2.5209, -1.0388,  1.3355],
        [ 0.5001, -0.5325,  0.6618],
        [-0.0260, -1.2217, -0.3268]])

In [20]:
torch.normal(mean=torch.full([10],0.), std=torch.arange(1, 0, -0.1))
# 均值means是一个张量，包含每个输出元素相关的正态分布的均值。
# std是一个张量，包含每个输出元素相关的正态分布的标准差。

tensor([ 1.6792,  1.8682,  1.0909, -0.2882,  0.0239,  0.5020, -0.7913, -0.0848,
        -0.0554,  0.0363])

In [21]:
torch.full([2,3],7)  # 以元素7填充shape为[2,3]的tensor

tensor([[7, 7, 7],
        [7, 7, 7]])

In [22]:
torch.full([],7)  # 以元素7填充dim=0的标量

tensor(7)

In [23]:
torch.full([1],7)  # 以元素7来填充shape为[1]的向量

tensor([7])

In [24]:
torch.arange(0,10)  # 生成[0,10)公差为1(默认)的等差数列

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
torch.arange(0,10,2)  # 生成[0,10)公差为2的等差数列

tensor([0, 2, 4, 6, 8])

In [26]:
torch.range(0,10)  # 一般不使用range()而使用arange()
'''
torch.range()和torch.arange()的区别:(在pytorch中 ，torch.arange更官方)
1.torch.arange()左闭右开，而torch.range()是左右都闭
2.torch.arange()可以单独写一个数值，表示0开始到该数结束的张量，而torch.range()不行
'''

C:\Users\fufu\AppData\Local\Temp\ipykernel_18180\1966223853.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)  # 一般不使用range()而使用arange()


'\ntorch.range()和torch.arange()的区别:(在pytorch中 ，torch.arange更官方)\n1.torch.arange()左闭右开，而torch.range()是左右都闭\n2.torch.arange()可以单独写一个数值，表示0开始到该数结束的张量，而torch.range()不行\n'

In [27]:
torch.linspace(0,10, steps=4)  # 生成[0,10]范围内元素数量为4的等差数列

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [28]:
torch.linspace(0,10, steps=10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [29]:
torch.linspace(0,10, steps=11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [30]:
torch.logspace(0,-1, steps=10)  # 生成以[-1,0]范围内元素数量为10的等差数列为真数,10(默认)为底数的数列

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

In [31]:
torch.logspace(0,1, steps=10)

tensor([ 1.0000,  1.2915,  1.6681,  2.1544,  2.7826,  3.5938,  4.6416,  5.9948,
         7.7426, 10.0000])

In [32]:
torch.ones(3,3)  # 生成size为(3,3)元素全为1的tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [33]:
torch.zeros(3,3)  # 生成size为(3,3)元素全为0的tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [34]:
torch.eye(3,4)  # 生成(3,4)对角矩阵

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [35]:
torch.eye(3)  # 生成(3,3)的对角矩阵

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [36]:
a=torch.zeros(3,3)

In [37]:
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [38]:
torch.randperm(10)  # 生成[0,10)的向量并打乱元素顺序

tensor([9, 6, 0, 3, 8, 7, 4, 2, 1, 5])

In [39]:
# 在某一维度上打乱元素顺序

# 例如:要在第1维上打乱
a=torch.rand(2,3)
b=torch.rand(4,3)
# 生成一个与第1维元素个数相同的种子tensor
idx=torch.randperm(3)
a,b,idx

(tensor([[0.3106, 0.0081, 0.1098],
         [0.5407, 0.4745, 0.1687]]),
 tensor([[0.0416, 0.1859, 0.2276],
         [0.6827, 0.7462, 0.2600],
         [0.7421, 0.5996, 0.3624],
         [0.4677, 0.2343, 0.7686]]),
 tensor([0, 2, 1]))

In [40]:
# 依照种子tensor来打乱a,b的第1维
a[:,idx]

tensor([[0.3106, 0.1098, 0.0081],
        [0.5407, 0.1687, 0.4745]])

In [41]:
b[:,idx]

tensor([[0.0416, 0.2276, 0.1859],
        [0.6827, 0.2600, 0.7462],
        [0.7421, 0.3624, 0.5996],
        [0.4677, 0.7686, 0.2343]])

In [42]:
a,b

(tensor([[0.3106, 0.0081, 0.1098],
         [0.5407, 0.4745, 0.1687]]),
 tensor([[0.0416, 0.1859, 0.2276],
         [0.6827, 0.7462, 0.2600],
         [0.7421, 0.5996, 0.3624],
         [0.4677, 0.2343, 0.7686]]))