In [1]:
import numpy as np
import torch

In [2]:
# randn() 生成标准正态分布的伪随机数（均值为0，方差为1）
a = torch.randn(2, 3)

In [3]:
a.type()

'torch.FloatTensor'

In [4]:
type(a)

torch.Tensor

In [5]:
isinstance(a,torch.FloatTensor)

True

In [6]:
isinstance(a, torch.cuda.DoubleTensor)

False

In [7]:
# 创建dim=0的tensor
torch.tensor(1.)

tensor(1.)

In [8]:
torch.tensor(1.3)

tensor(1.3000)

In [9]:
a=torch.tensor(2.2)

In [10]:
a.shape

torch.Size([])

In [11]:
len(a.shape),a.dim()

(0, 0)

In [12]:
a.size()

# shape与size()的区别：
# shape是作为一个成员；size()是作为一个成员函数。

torch.Size([])

In [13]:
# 创建dim=1的tensor,即标量（一般用于表示bias或batch_size=1的一张图片）
torch.tensor([1.1])

tensor([1.1000])

In [14]:
torch.tensor([1.1, 2.2])

tensor([1.1000, 2.2000])

In [15]:
torch.FloatTensor(1)  # 相当于randn()初始化

tensor([-1.0842e-19])

In [16]:
torch.FloatTensor(2)

tensor([1.4372e-33, 4.5914e-41])

In [17]:
data=np.ones(2)

In [18]:
data

array([1., 1.])

In [19]:
torch.from_numpy(data)

tensor([1., 1.], dtype=torch.float64)

In [20]:
a=torch.ones(2)

In [21]:
a.shape

torch.Size([2])

In [22]:
# 创建dim=2的tensor，即向量
#（一般用于带有batch的Linear输入）
a=torch.randn(2,3)

In [23]:
a

tensor([[ 0.1696,  0.9777,  1.2449],
        [-1.1541,  0.8504, -0.7611]])

In [24]:
a.shape

torch.Size([2, 3])

In [25]:
a.size()

torch.Size([2, 3])

In [26]:
a.size(0),a.size(1)  # 分别取a的第0维和第1维的形状

(2, 3)

In [27]:
a.shape[0],a.shape[1]  # 同上

(2, 3)

In [28]:
# dim=3的tensor（一般用于文字处理RNN）
# rand() 生成均匀分布的伪随机数。分布在（0~1）之间
a=torch.rand(1,2,3)

In [29]:
a

tensor([[[0.4891, 0.2711, 0.9136],
         [0.9264, 0.2842, 0.7692]]])

In [30]:
a.shape

torch.Size([1, 2, 3])

In [31]:
a[0]  # 取a的第0维

tensor([[0.4891, 0.2711, 0.9136],
        [0.9264, 0.2842, 0.7692]])

In [32]:
list(a.shape)  # 转化为list类型

[1, 2, 3]

In [33]:
# dim=4的tensor（一般用于一组图片的输入[batch_size,color,h,w）
a=torch.rand(2,3,28,28)

In [34]:
a

tensor([[[[0.1700, 0.8824, 0.9286,  ..., 0.2337, 0.4681, 0.7022],
          [0.5295, 0.3699, 0.5390,  ..., 0.2420, 0.9210, 0.7975],
          [0.6690, 0.2382, 0.6836,  ..., 0.2081, 0.6303, 0.4481],
          ...,
          [0.1402, 0.7553, 0.4565,  ..., 0.2059, 0.3989, 0.7161],
          [0.3058, 0.3217, 0.1779,  ..., 0.0062, 0.2528, 0.6921],
          [0.2950, 0.6845, 0.3909,  ..., 0.4200, 0.7325, 0.5610]],

         [[0.5331, 0.7246, 0.7206,  ..., 0.8349, 0.7148, 0.7713],
          [0.4471, 0.3777, 0.7259,  ..., 0.7479, 0.0523, 0.0267],
          [0.6801, 0.0806, 0.9773,  ..., 0.2840, 0.0533, 0.2858],
          ...,
          [0.3337, 0.9049, 0.9123,  ..., 0.0688, 0.6822, 0.8078],
          [0.5981, 0.8082, 0.8856,  ..., 0.2629, 0.1498, 0.4635],
          [0.2845, 0.6430, 0.7104,  ..., 0.3322, 0.8835, 0.1822]],

         [[0.9538, 0.6015, 0.6900,  ..., 0.3523, 0.8922, 0.4320],
          [0.3726, 0.5788, 0.5092,  ..., 0.9924, 0.2337, 0.3706],
          [0.8967, 0.8497, 0.5046,  ..., 0

In [35]:
a.shape

torch.Size([2, 3, 28, 28])

In [36]:
torch.Size([2,3,28,28])

torch.Size([2, 3, 28, 28])

In [37]:
a.shape

torch.Size([2, 3, 28, 28])

In [38]:
a.numel()  # 返回tensor所占内存的数量（number_of_element）

4704

In [39]:
a.dim()

4

In [40]:
a=torch.tensor(1)

In [41]:
a.dim()

0