In [1]:
import numpy as np
import torch

In [2]:
a=torch.rand(4,3,28,28)
a[0].shape,a[0,0].shape,a[0,0,2,4]

(torch.Size([3, 28, 28]), torch.Size([28, 28]), tensor(0.1591))

In [3]:
a.shape

torch.Size([4, 3, 28, 28])

In [4]:
# 1.连续选取

a[:2].shape  # 选取第0维上第[0(开头),2)个元素

torch.Size([2, 3, 28, 28])

In [5]:
a[:2,:1,:,:].shape  # 选取第0维上第[0(开头),2)个,第1维上第[0,1)个元素

torch.Size([2, 1, 28, 28])

In [6]:
a[:2,1:,:,:].shape  # 选取第0维上第[0(开头),2)个,第1维上第[1,4(末尾))个,第2第3维全部元素

torch.Size([2, 2, 28, 28])

In [7]:
a[:2,-1:,:,:].shape  # 选取第0维上第[0(开头),2)个,第1维上第[-1(倒数第1个),4(末尾))个,第2第3维全部元素

torch.Size([2, 1, 28, 28])

In [8]:
a[:,:,0:28:2,0:28:2].shape  # 选取第0第1维全部元素,第2维上步长为2地取第[0,28)个元素,第3维上步长为2地取第[0,28)个元素

torch.Size([4, 3, 14, 14])

In [9]:
a[:,:,::2,::2].shape  # 选取第0第1维全部元素,第2第3维上步长为2地取全部元素

torch.Size([4, 3, 14, 14])

In [10]:
a.shape

torch.Size([4, 3, 28, 28])

In [11]:
# 2.维度选取:.index_select()

a.index_select(0, torch.tensor([0,2])).shape  # 选取第0维上的第0第2个元素

torch.Size([2, 3, 28, 28])

In [12]:
a.index_select(1, torch.tensor([0,2])).shape

torch.Size([4, 2, 28, 28])

In [13]:
a.index_select(2, torch.arange(28)).shape  # 选取第2维上的第[0,28)个元素

torch.Size([4, 3, 28, 28])

In [14]:
a.index_select(2, torch.arange(8)).shape

torch.Size([4, 3, 8, 28])

In [15]:
a.shape

torch.Size([4, 3, 28, 28])

In [16]:
# 3.全部选取:...

a[...].shape  # 取全部元素

torch.Size([4, 3, 28, 28])

In [17]:
a[0,...].shape  # 取第0维上的第1个元素

torch.Size([3, 28, 28])

In [18]:
a[:,1,...].shape

torch.Size([4, 28, 28])

In [19]:
a[...,:2].shape

torch.Size([4, 3, 28, 2])

In [20]:
x = torch.randn(3,4)
x

tensor([[-0.4783,  0.5642, -1.2406,  1.6677],
        [ 1.0866,  1.1457,  0.6399, -0.3683],
        [-1.0570, -0.8665,  1.7044,  0.7345]])

In [21]:
# 4.使用mask掩码索引
torch.ge
mask = x.ge(0.5)  # 返回一个tensor其中元素为x与0.5大小比较的结果
mask

tensor([[False,  True, False,  True],
        [ True,  True,  True, False],
        [False, False,  True,  True]])

In [22]:
torch.masked_select(x, mask)  
'''根据掩码（mask）对输入的张量进行选择，返回一个新的张量。
它可以根据提供的掩码参数，选择出输入张量中被掩码为True的元素，
并将其转换为一个一维的张量，其中每个元素在原始输入中的下标也会被记录。'''

'根据掩码（mask）对输入的张量进行选择，返回一个新的张量。\n它可以根据提供的掩码参数，选择出输入张量中被掩码为True的元素，\n并将其转换为一个一维的张量，其中每个元素在原始输入中的下标也会被记录。'

In [23]:
torch.masked_select(x, mask).shape

torch.Size([7])

In [24]:
src = torch.tensor([[4,3,5],[6,7,8]])
# 5.使用take()索引
torch.take(src, torch.tensor([0, 2, 5]))  # 先将src打平再选取第0,2,5个元素

tensor([4, 5, 8])